import { Info } from "lucide-react";
import Card from "../common/Card";
import Badge from "../common/Badge";
import type { Reasoning, ReasoningLink } from "../../types/analysis";

interface ReasoningCardProps {
  reasoning: Reasoning;
  /** Activate a context link (highlights/scrolls the evidence section). */
  onSelectLink?: (link: ReasoningLink, index: number) => void;
  activeLinkIndex?: number | null;
}

/**
 * "Why this was classified this way" — the context-relationship reasoning
 * section. Renders the backend's deterministic reasoning block: how the
 * previous comment relates to the current comment, the pronoun -> antecedent
 * connections, and per-source evidence. Never generated by a language model.
 */
export default function ReasoningCard({
  reasoning,
  onSelectLink,
  activeLinkIndex = null,
}: ReasoningCardProps) {
  return (
    <Card
      title="Why this was classified this way"
      titleIcon={<Info className="h-3.5 w-3.5" aria-hidden="true" />}
      action={
        reasoning.context_used ? (
          <Badge tone="info">context used</Badge>
        ) : (
          <Badge tone="neutral">comment only</Badge>
        )
      }
      className="!border-accent/30"
    >
      <p className="max-w-[75ch] text-sm leading-relaxed text-ink">
        {reasoning.summary}
      </p>

      {reasoning.links.length > 0 ? (
        <div className="mt-4">
          <p className="kicker">Context connection</p>
          <ul className="mt-2 flex flex-wrap gap-2">
            {reasoning.links.map((link, index) => (
              <li key={`${link.pronoun}-${link.from_start}-${link.to_start}`}>
                <button
                  type="button"
                  onClick={() => onSelectLink?.(link, index)}
                  className={[
                    "inline-flex max-w-full items-center gap-2 rounded-md border px-2.5 py-1.5 text-left text-xs transition-colors",
                    activeLinkIndex === index
                      ? "border-accent bg-accent/15 text-ink"
                      : "border-edge bg-panel text-ink-soft hover:bg-raised hover:text-ink",
                  ].join(" ")}
                  aria-label={`Show connection: ${link.from_text} refers to ${link.to_text}`}
                >
                  <span className="font-mono text-accent">{link.from_text}</span>
                  <span className="text-ink-mute" aria-hidden="true">
                    →
                  </span>
                  <span className="min-w-0 break-words">“{link.to_text}”</span>
                </button>
              </li>
            ))}
          </ul>
          <p className="mt-2 text-[11px] text-ink-mute/80">
            Reference analysis: the highlighted word in the current comment
            points back to the phrase in the previous comment (deterministic
            heuristic with character offsets — not model attention).
          </p>
        </div>
      ) : null}

      {reasoning.evidence.length > 0 ? (
        <div className="mt-4">
          <p className="kicker">Evidence &amp; sources</p>
          <ul className="mt-2 space-y-2">
            {reasoning.evidence.map((item, index) => (
              <li
                key={`${item.source}-${index}`}
                className="flex flex-wrap items-baseline gap-x-2 gap-y-0.5 text-sm"
              >
                <Badge tone={item.source === "previous_comment" ? "neutral" : "info"}>
                  {item.source === "previous_comment"
                    ? "previous comment"
                    : "current comment"}
                </Badge>
                <span className="min-w-0 break-words text-ink">“{item.text}”</span>
                {item.reason ? (
                  <span className="text-xs text-ink-mute">{item.reason}</span>
                ) : null}
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      <p className="mt-4 text-[11px] leading-relaxed text-ink-mute/80">
        Classification from the trained model; evidence from attribution and a
        deterministic context analysis ({reasoning.method}) — not by a language
        model.
      </p>
    </Card>
  );
}
