import { BookOpen } from "lucide-react";
import PageContainer from "../components/layout/PageContainer";

interface Section {
  title: string;
  paragraphs: string[];
}

const SECTIONS: Section[] = [
  {
    title: "What is this?",
    paragraphs: [
      "An interface for a research prototype: a context-aware hate speech classifier built on a fine-tuned BERT encoder.",
      "For a comment (and optionally the preceding message) it returns a structured result: the hate/offensive/normal prediction, a target group, a reason category, and the text spans that contributed most strongly to the prediction.",
    ],
  },
  {
    title: "Why context matters",
    paragraphs: [
      "The meaning of a message often depends on what was said before it. “They are ruining everything.” reads very differently after “Why are you talking about immigrants?” than after “The wifi keeps dropping”.",
      "The model therefore receives the current comment together with its conversational context and is trained to use it.",
    ],
  },
  {
    title: "How BERT is used",
    paragraphs: [
      "We do not train BERT from scratch. We use a pretrained BERT encoder and fine-tune it for this task.",
      "BERT provides contextual language representations: every token is represented relative to the whole input, and the special [CLS] representation summarises the comment (or the context).",
    ],
  },
  {
    title: "Context interaction",
    paragraphs: [
      "The current comment and the context pass through the same encoder — the weights are shared, so both embeddings live in the same semantic space.",
      "Their embeddings are combined with explicit interaction features: D = |E_c − E_p| (absolute difference) and M = E_c ⊙ E_p (element-wise product), concatenated with the two embeddings and passed through a small neural layer.",
    ],
  },
  {
    title: "Contrastive learning",
    paragraphs: [
      "During training, the model learns to distinguish a comment's real context from a contrasting (mismatched) context, using an InfoNCE-style objective.",
      "This encourages context-aware representations. It is a training-only technique — inference only produces the context-aware representation.",
    ],
  },
  {
    title: "Structured reasoning",
    paragraphs: [
      "The system does not generate free-form reasoning. It provides structured predictions and attribution-based evidence.",
      "WHAT → prediction · WHO → target · WHY / WHAT TYPE → reason · WHICH WORDS → evidence · DID CONTEXT MATTER → context flag. This structured combination is the reasoning output.",
    ],
  },
  {
    title: "Evidence extraction",
    paragraphs: [
      "Evidence spans are computed with Integrated Gradients: the model's prediction is attributed back to the input tokens, and high-contribution adjacent tokens are merged into readable phrases.",
      "Evidence is attribution-based — it is not a human-verified causal explanation, and it is not generated by a language model.",
    ],
  },
  {
    title: "Reason explanation",
    paragraphs: [
      "After evidence extraction, a deterministic explanation layer connects the model's predicted reason category to the evidence that was actually extracted.",
      "The explanation is generated from structured outputs — the predicted reason, the predicted target, and the extracted evidence spans — and never introduces information that is not present in those fields.",
      "The system does not generate free-form reasoning with an LLM. The explanation is grounded in the model's structured outputs and extracted evidence, and it describes the classification rather than the author's intent.",
    ],
  },
  {
    title: "Datasets",
    paragraphs: [
      "HateXplain (primary): hate/offensive/normal labels, target communities, and token-level rationale annotations used to evaluate evidence extraction.",
      "Counter Context (NAACL 2022): comments paired with their preceding conversational context, used for context-dependent and contrastive experiments.",
      "The datasets are handled by separate adapters and are not merged blindly.",
    ],
  },
  {
    title: "Limitations",
    paragraphs: [
      "Model predictions are probabilistic.",
      "Evidence represents attribution signals, not human-verified causal reasoning.",
      "Context can influence classification but does not guarantee correctness.",
      "Reason classification requires appropriate reason-annotated training data.",
      "The model may inherit biases or errors from its training data.",
      "Predictions should not be treated as definitive judgments about people.",
    ],
  },
];

export default function AboutPage() {
  return (
    <PageContainer className="max-w-4xl">
      <div className="max-w-3xl">
        <p className="kicker flex items-center gap-2">
          <BookOpen className="h-3.5 w-3.5" aria-hidden="true" />
          about the project
        </p>
        <h1 className="mt-2 text-2xl font-semibold tracking-tight text-ink sm:text-3xl">
          Context-Aware Hate Speech Detection with Structured Evidence-Based
          Reasoning
        </h1>
        <p className="mt-3 text-sm leading-relaxed text-ink-soft">
          A research prototype that shows how a context-aware Transformer
          model classifies a comment — and which parts of the text its
          decision is grounded in.
        </p>
      </div>

      <div className="mt-10 space-y-8">
        {SECTIONS.map((section) => (
          <section key={section.title}>
            <h2 className="border-b border-edge pb-2 text-base font-semibold tracking-tight text-ink">
              {section.title}
            </h2>
            <div className="mt-3 space-y-2">
              {section.paragraphs.map((paragraph) => (
                <p
                  key={paragraph}
                  className="max-w-[75ch] text-sm leading-relaxed text-ink-soft"
                >
                  {paragraph}
                </p>
              ))}
            </div>
          </section>
        ))}
      </div>

      <p className="mt-10 border-t border-edge pt-4 text-[11px] text-ink-mute">
        This interface never performs classification or reasoning on its own —
        every prediction and every evidence span comes from the backend model.
      </p>
    </PageContainer>
  );
}
